/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) turbine_impl_dae_fun_jac_x_xdot_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[3] = {0, 0, 0};
static const casadi_int casadi_s4[9] = {3, 3, 0, 1, 2, 3, 0, 0, 0};
static const casadi_int casadi_s5[9] = {3, 3, 0, 1, 2, 3, 0, 1, 2};
static const casadi_int casadi_s6[3] = {3, 0, 0};

/* turbine_impl_dae_fun_jac_x_xdot_z:(i0[3],i1[3],i2[2],i3[0],i4[],i5[0])->(o0[3],o1[3x3,3nz],o2[3x3,3nz],o3[3x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[1]? arg[1][0] : 0;
  a1=2.8306046446089535e-05;
  a2=9.0973773732493725e+05;
  a3=5.1759999999999995e-01;
  a4=116.;
  a5=6.1500000000000000e+01;
  a6=arg[0]? arg[0][0] : 0;
  a7=(a5*a6);
  a8=5.;
  a7=(a7/a8);
  a9=8.0000000000000002e-02;
  a10=arg[0]? arg[0][1] : 0;
  a11=(a9*a10);
  a11=(a7+a11);
  a12=(1./a11);
  a13=3.5000000000000003e-02;
  a14=casadi_sq(a10);
  a15=(a10*a14);
  a16=1.;
  a15=(a15+a16);
  a13=(a13/a15);
  a17=(a12-a13);
  a18=(a4*a17);
  a19=4.0000000000000002e-01;
  a20=(a19*a10);
  a18=(a18-a20);
  a18=(a18-a8);
  a18=(a3*a18);
  a8=-21.;
  a17=(a8*a17);
  a17=exp(a17);
  a20=(a18*a17);
  a21=6.7999999999999996e-03;
  a7=(a21*a7);
  a20=(a20+a7);
  a20=(a2*a20);
  a7=1000.;
  a6=(a7*a6);
  a20=(a20/a6);
  a22=arg[0]? arg[0][2] : 0;
  a22=(a20-a22);
  a22=(a1*a22);
  a0=(a0-a22);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[1]? arg[1][1] : 0;
  a22=arg[2]? arg[2][0] : 0;
  a0=(a0-a22);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[1]? arg[1][2] : 0;
  a22=arg[2]? arg[2][1] : 0;
  a0=(a0-a22);
  if (res[0]!=0) res[0][2]=a0;
  a0=2.0000000000000001e-01;
  a22=-2.8306046446089535e-05;
  a23=(a22/a6);
  a2=(a2*a23);
  a21=(a21*a2);
  a12=(a12/a11);
  a18=(a18*a2);
  a18=(a17*a18);
  a8=(a8*a18);
  a17=(a17*a2);
  a3=(a3*a17);
  a4=(a4*a3);
  a8=(a8+a4);
  a12=(a12*a8);
  a21=(a21-a12);
  a0=(a0*a21);
  a5=(a5*a0);
  a20=(a20/a6);
  a22=(a22*a20);
  a7=(a7*a22);
  a5=(a5-a7);
  if (res[1]!=0) res[1][0]=a5;
  a13=(a13/a15);
  a13=(a13*a8);
  a14=(a14*a13);
  a19=(a19*a3);
  a14=(a14-a19);
  a19=(a10+a10);
  a10=(a10*a13);
  a19=(a19*a10);
  a14=(a14+a19);
  a9=(a9*a12);
  a14=(a14-a9);
  if (res[1]!=0) res[1][1]=a14;
  if (res[1]!=0) res[1][2]=a1;
  if (res[2]!=0) res[2][0]=a16;
  if (res[2]!=0) res[2][1]=a16;
  if (res[2]!=0) res[2][2]=a16;
  return 0;
}

CASADI_SYMBOL_EXPORT int turbine_impl_dae_fun_jac_x_xdot_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int turbine_impl_dae_fun_jac_x_xdot_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int turbine_impl_dae_fun_jac_x_xdot_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void turbine_impl_dae_fun_jac_x_xdot_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int turbine_impl_dae_fun_jac_x_xdot_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void turbine_impl_dae_fun_jac_x_xdot_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void turbine_impl_dae_fun_jac_x_xdot_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void turbine_impl_dae_fun_jac_x_xdot_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int turbine_impl_dae_fun_jac_x_xdot_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int turbine_impl_dae_fun_jac_x_xdot_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real turbine_impl_dae_fun_jac_x_xdot_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* turbine_impl_dae_fun_jac_x_xdot_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* turbine_impl_dae_fun_jac_x_xdot_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* turbine_impl_dae_fun_jac_x_xdot_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    case 5: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* turbine_impl_dae_fun_jac_x_xdot_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int turbine_impl_dae_fun_jac_x_xdot_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int turbine_impl_dae_fun_jac_x_xdot_z_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
