/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) turbine_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s2[11] = {3, 2, 0, 3, 6, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s3[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s4[4] = {0, 1, 0, 0};

/* turbine_expl_vde_forw:(i0[3],i1[3x3],i2[3x2],i3[2],i4[0])->(o0[3],o1[3x3],o2[3x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a3, a4, a5, a6, a7, a8, a9;
  a0=2.8306046446089535e-05;
  a1=1.9650335126218645e+05;
  a2=5.1759999999999995e-01;
  a3=116.;
  a4=6.1500000000000000e+01;
  a5=arg[0]? arg[0][0] : 0;
  a6=(a4*a5);
  a7=3.;
  a6=(a6/a7);
  a7=8.0000000000000002e-02;
  a8=arg[0]? arg[0][1] : 0;
  a9=(a7*a8);
  a9=(a6+a9);
  a10=(1./a9);
  a11=3.5000000000000003e-02;
  a12=casadi_sq(a8);
  a13=(a8*a12);
  a14=1.;
  a13=(a13+a14);
  a11=(a11/a13);
  a15=(a10-a11);
  a16=(a3*a15);
  a17=4.0000000000000002e-01;
  a18=(a17*a8);
  a16=(a16-a18);
  a18=5.;
  a16=(a16-a18);
  a16=(a2*a16);
  a18=-21.;
  a15=(a18*a15);
  a15=exp(a15);
  a19=(a16*a15);
  a20=6.7999999999999996e-03;
  a6=(a20*a6);
  a19=(a19+a6);
  a19=(a1*a19);
  a6=1000.;
  a5=(a6*a5);
  a19=(a19/a5);
  a21=arg[0]? arg[0][2] : 0;
  a21=(a19-a21);
  a21=(a0*a21);
  if (res[0]!=0) res[0][0]=a21;
  a21=arg[3]? arg[3][0] : 0;
  if (res[0]!=0) res[0][1]=a21;
  a21=arg[3]? arg[3][1] : 0;
  if (res[0]!=0) res[0][2]=a21;
  a11=(a11/a13);
  a13=arg[1]? arg[1][1] : 0;
  a21=(a12*a13);
  a22=(a8+a8);
  a23=(a22*a13);
  a23=(a8*a23);
  a21=(a21+a23);
  a21=(a11*a21);
  a10=(a10/a9);
  a9=3.3333333333333331e-01;
  a23=arg[1]? arg[1][0] : 0;
  a24=(a4*a23);
  a24=(a9*a24);
  a25=(a7*a13);
  a25=(a24+a25);
  a25=(a10*a25);
  a21=(a21-a25);
  a25=(a3*a21);
  a13=(a17*a13);
  a25=(a25-a13);
  a25=(a2*a25);
  a25=(a15*a25);
  a21=(a18*a21);
  a21=(a15*a21);
  a21=(a16*a21);
  a25=(a25+a21);
  a24=(a20*a24);
  a25=(a25+a24);
  a25=(a1*a25);
  a25=(a25/a5);
  a19=(a19/a5);
  a23=(a6*a23);
  a23=(a19*a23);
  a25=(a25-a23);
  a23=arg[1]? arg[1][2] : 0;
  a25=(a25-a23);
  a25=(a0*a25);
  if (res[1]!=0) res[1][0]=a25;
  a25=0.;
  if (res[1]!=0) res[1][1]=a25;
  if (res[1]!=0) res[1][2]=a25;
  a23=arg[1]? arg[1][4] : 0;
  a24=(a12*a23);
  a21=(a22*a23);
  a21=(a8*a21);
  a24=(a24+a21);
  a24=(a11*a24);
  a21=arg[1]? arg[1][3] : 0;
  a13=(a4*a21);
  a13=(a9*a13);
  a26=(a7*a23);
  a26=(a13+a26);
  a26=(a10*a26);
  a24=(a24-a26);
  a26=(a3*a24);
  a23=(a17*a23);
  a26=(a26-a23);
  a26=(a2*a26);
  a26=(a15*a26);
  a24=(a18*a24);
  a24=(a15*a24);
  a24=(a16*a24);
  a26=(a26+a24);
  a13=(a20*a13);
  a26=(a26+a13);
  a26=(a1*a26);
  a26=(a26/a5);
  a21=(a6*a21);
  a21=(a19*a21);
  a26=(a26-a21);
  a21=arg[1]? arg[1][5] : 0;
  a26=(a26-a21);
  a26=(a0*a26);
  if (res[1]!=0) res[1][3]=a26;
  if (res[1]!=0) res[1][4]=a25;
  if (res[1]!=0) res[1][5]=a25;
  a26=arg[1]? arg[1][7] : 0;
  a21=(a12*a26);
  a13=(a22*a26);
  a13=(a8*a13);
  a21=(a21+a13);
  a21=(a11*a21);
  a13=arg[1]? arg[1][6] : 0;
  a24=(a4*a13);
  a24=(a9*a24);
  a23=(a7*a26);
  a23=(a24+a23);
  a23=(a10*a23);
  a21=(a21-a23);
  a23=(a3*a21);
  a26=(a17*a26);
  a23=(a23-a26);
  a23=(a2*a23);
  a23=(a15*a23);
  a21=(a18*a21);
  a21=(a15*a21);
  a21=(a16*a21);
  a23=(a23+a21);
  a24=(a20*a24);
  a23=(a23+a24);
  a23=(a1*a23);
  a23=(a23/a5);
  a13=(a6*a13);
  a13=(a19*a13);
  a23=(a23-a13);
  a13=arg[1]? arg[1][8] : 0;
  a23=(a23-a13);
  a23=(a0*a23);
  if (res[1]!=0) res[1][6]=a23;
  if (res[1]!=0) res[1][7]=a25;
  if (res[1]!=0) res[1][8]=a25;
  a23=arg[2]? arg[2][1] : 0;
  a13=(a12*a23);
  a24=(a22*a23);
  a24=(a8*a24);
  a13=(a13+a24);
  a13=(a11*a13);
  a24=arg[2]? arg[2][0] : 0;
  a21=(a4*a24);
  a21=(a9*a21);
  a26=(a7*a23);
  a26=(a21+a26);
  a26=(a10*a26);
  a13=(a13-a26);
  a26=(a3*a13);
  a23=(a17*a23);
  a26=(a26-a23);
  a26=(a2*a26);
  a26=(a15*a26);
  a13=(a18*a13);
  a13=(a15*a13);
  a13=(a16*a13);
  a26=(a26+a13);
  a21=(a20*a21);
  a26=(a26+a21);
  a26=(a1*a26);
  a26=(a26/a5);
  a24=(a6*a24);
  a24=(a19*a24);
  a26=(a26-a24);
  a24=arg[2]? arg[2][2] : 0;
  a26=(a26-a24);
  a26=(a0*a26);
  if (res[2]!=0) res[2][0]=a26;
  if (res[2]!=0) res[2][1]=a14;
  if (res[2]!=0) res[2][2]=a25;
  a26=arg[2]? arg[2][4] : 0;
  a12=(a12*a26);
  a22=(a22*a26);
  a8=(a8*a22);
  a12=(a12+a8);
  a11=(a11*a12);
  a12=arg[2]? arg[2][3] : 0;
  a4=(a4*a12);
  a9=(a9*a4);
  a7=(a7*a26);
  a7=(a9+a7);
  a10=(a10*a7);
  a11=(a11-a10);
  a3=(a3*a11);
  a17=(a17*a26);
  a3=(a3-a17);
  a2=(a2*a3);
  a2=(a15*a2);
  a18=(a18*a11);
  a15=(a15*a18);
  a16=(a16*a15);
  a2=(a2+a16);
  a20=(a20*a9);
  a2=(a2+a20);
  a1=(a1*a2);
  a1=(a1/a5);
  a6=(a6*a12);
  a19=(a19*a6);
  a1=(a1-a19);
  a19=arg[2]? arg[2][5] : 0;
  a1=(a1-a19);
  a0=(a0*a1);
  if (res[2]!=0) res[2][3]=a0;
  if (res[2]!=0) res[2][4]=a25;
  if (res[2]!=0) res[2][5]=a14;
  return 0;
}

CASADI_SYMBOL_EXPORT int turbine_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int turbine_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int turbine_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void turbine_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int turbine_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void turbine_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void turbine_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void turbine_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int turbine_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int turbine_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real turbine_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* turbine_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* turbine_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* turbine_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* turbine_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int turbine_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int turbine_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
