/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) turbine_gnsf_phi_fun_jac_y_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s1[4] = {0, 1, 0, 0};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s3[7] = {1, 2, 0, 1, 2, 0, 0};

/* turbine_gnsf_phi_fun_jac_y:(i0[2],i1[0],i2[0])->(o0,o1[1x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=-2.8306046446089535e-05;
  a1=1.9650335126218645e+05;
  a2=5.1759999999999995e-01;
  a3=116.;
  a4=6.1500000000000000e+01;
  a5=arg[0]? arg[0][0] : 0;
  a4=(a4*a5);
  a6=3.;
  a4=(a4/a6);
  a6=8.0000000000000002e-02;
  a7=arg[0]? arg[0][1] : 0;
  a8=(a6*a7);
  a8=(a4+a8);
  a9=(1./a8);
  a10=3.5000000000000003e-02;
  a11=casadi_sq(a7);
  a12=(a7*a11);
  a13=1.;
  a12=(a12+a13);
  a10=(a10/a12);
  a13=(a9-a10);
  a14=(a3*a13);
  a15=4.0000000000000002e-01;
  a15=(a15*a7);
  a14=(a14-a15);
  a15=5.;
  a14=(a14-a15);
  a14=(a2*a14);
  a15=-21.;
  a13=(a15*a13);
  a13=exp(a13);
  a16=(a14*a13);
  a17=6.7999999999999996e-03;
  a17=(a17*a4);
  a16=(a16+a17);
  a16=(a1*a16);
  a17=1000.;
  a5=(a17*a5);
  a16=(a16/a5);
  a4=(a0*a16);
  if (res[0]!=0) res[0][0]=a4;
  a4=1.3940000000000000e-01;
  a18=2.0500000000000000e+01;
  a9=(a9/a8);
  a18=(a18*a9);
  a8=(a3*a18);
  a8=(a2*a8);
  a8=(a13*a8);
  a18=(a15*a18);
  a18=(a13*a18);
  a18=(a14*a18);
  a8=(a8+a18);
  a4=(a4-a8);
  a4=(a1*a4);
  a4=(a4/a5);
  a16=(a16/a5);
  a17=(a17*a16);
  a4=(a4-a17);
  a4=(a0*a4);
  if (res[1]!=0) res[1][0]=a4;
  a10=(a10/a12);
  a12=(a7+a7);
  a7=(a7*a12);
  a11=(a11+a7);
  a10=(a10*a11);
  a6=(a6*a9);
  a10=(a10-a6);
  a3=(a3*a10);
  a6=-4.0000000000000002e-01;
  a3=(a3+a6);
  a2=(a2*a3);
  a2=(a13*a2);
  a15=(a15*a10);
  a13=(a13*a15);
  a14=(a14*a13);
  a2=(a2+a14);
  a1=(a1*a2);
  a1=(a1/a5);
  a0=(a0*a1);
  if (res[1]!=0) res[1][1]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int turbine_gnsf_phi_fun_jac_y(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int turbine_gnsf_phi_fun_jac_y_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int turbine_gnsf_phi_fun_jac_y_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void turbine_gnsf_phi_fun_jac_y_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int turbine_gnsf_phi_fun_jac_y_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void turbine_gnsf_phi_fun_jac_y_release(int mem) {
}

CASADI_SYMBOL_EXPORT void turbine_gnsf_phi_fun_jac_y_incref(void) {
}

CASADI_SYMBOL_EXPORT void turbine_gnsf_phi_fun_jac_y_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int turbine_gnsf_phi_fun_jac_y_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int turbine_gnsf_phi_fun_jac_y_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real turbine_gnsf_phi_fun_jac_y_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* turbine_gnsf_phi_fun_jac_y_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* turbine_gnsf_phi_fun_jac_y_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* turbine_gnsf_phi_fun_jac_y_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* turbine_gnsf_phi_fun_jac_y_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int turbine_gnsf_phi_fun_jac_y_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int turbine_gnsf_phi_fun_jac_y_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
